config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about', as: 'about'
  resources :books, only: [:index,:create,:show,:edit,:update,:destroy] do
    resource :favorite, only:[:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  validates :comment, presence: true
  
  belongs_to :user
  belongs_to :book
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  validates :user_id, uniqueness: {scope: :book_id}
  
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followerd, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :follwers, through: reverse_of_relationships, sorce: :follower
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :follweings, through: relationships, sorce: :followed

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end
  
  def destroy
    BookComment.find(params[:id]).destroy
    redirect_to book_path(params[:book_id])
  end
  
  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
 before_action :authenticate_user!
 before_action :ensure_correct_user, only: [:edit, :update]  
  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
      if @book.save
        flash[:notice] = "You have created book successfully. "
        redirect_to book_path(@book)
      else
        @books = Book.all
        render 'index'
      end
  end

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
      if @book.update(book_params)
        flash[:notice] = "You have updated book successfully. "
        redirect_to book_path(@book.id)
      else
        render 'edit'
      end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
  
  def ensure_correct_user
    book = Book.find(params[:id])
    unless book.user.id == current_user.id
      redirect_to books_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
   book = Book.find(params[:book_id])
   favorite = current_user.favorites.new(book_id: book.id)
   favorite.save
   redirect_to request.referer
  end
  
  def destroy
   book = Book.find(params[:book_id])
   favorite = current_user.favorites.find_by(book_id: book.id)
   favorite.destroy
   redirect_to request.referer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    
  end
  
  def about
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :authenticate_user!
 before_action :is_matching_login_user, only: [:edit, :update]  
  def index
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else 
      render 'edit'
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name,:introduction,:profile_image)
  end  
  
  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<table class="table table-hover table-invers">
  <thead>
    <tr>
      <th></th>
      <th>
        Title
      </th>
      <th>
        Opinion
      </th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user.id) do %>
            <%= image_tag book.user.get_profile_image(80,80) %>
          <% end %>
        </td>
        <td>
          <%= link_to book.title, book_path(book.id) %>
        </td>
        <td>
          <%= book.body %>
        </td>
        <td>
          <% if book.favorited_by?(current_user) %>
            <p>
              <%= link_to book_favorite_path(book), method: :delete do %>
                ♥<%= book.favorites.count %>
              <% end %>
            </p>
            <% else %>
            <p>
              <%= link_to book_favorite_path(book), method: :post do %>
                ♡<%= book.favorites.count %>
              <% end %>
            </p>
          <% end %>
        </td>
        <td>
          コメント数：<%= book.book_comments.count %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_new.html.erb
<h2 class="mt-3">New book</h1>

  <%= form_with model: book, url: books_path, method: :post do |f| %>
  <div class="form-group">
     <%= f.label :title %>
     <%= f.text_field :title, class:"form-control" %>
  </div>
  <div class="form-group">
     <%= f.label :opinion %>
     <%= f.text_area :body, class:"form-control" %>
  </div>
      <%= f.submit "Create Book", class:"btn btn-success" %>
  <% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Editing Book</h2>
        <% if @book.errors.any? %>
          <%= @book.errors.count %> errors prohibited this obj from being saved:
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
        <%= form_with model: @book, url: book_path(@book.id), method: :PATCH do |f| %>
          <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, class:"form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :opinion %>
            <%= f.text_area :body, class:"form-control" %>
          </div>
          <%= f.submit "Update Book", class:"btn btn-success" %>
        <% end %>
        
        <%= link_to "Show", book_path(@book.id) %>|<%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
<% if @book.errors.any? %>
  <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
 <div class="row">
   <div class="col-md-3">
     <%= render 'users/info', user: current_user %>
     <%= render 'new', book: @book %>
   </div>
   <div class="col-md-8 offset-md-1">
     <h2>Books</h2>
     <%= render 'list', books: @books %>
   </div>
 </div>
</div>

  

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
   <div class="col-md-3">
     <%= render 'users/info', user: @book.user %>
     <%= render 'new', book: @newbook %>
   </div>
   <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@book.user) do %>
                <%= image_tag @book.user.get_profile_image(100,100) %></br>
                <%= @book.user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to @book.title, book_path(@book.id) %>
            </td>
            <td>
              <%= @book.body %>
            </td>
            <td>
              <% if @book.favorited_by?(current_user) %>
                <p>
                  <%= link_to book_favorite_path(@book), method: :delete do %>
                    ♥<%= @book.favorites.count %>
                  <% end %>
                </p>
                <% else %>
                <p>
                  <%= link_to book_favorite_path(@book), method: :post do %>
                    ♡<%= @book.favorites.count %>
                  <% end %>
                </p>
              <% end %>
            </td>
            <td>
              コメント数：<%= @book.book_comments.count %>
            </td>
            <% if @book.user == current_user %>
              <td>
                <%= link_to "Edit", edit_book_path(@book.id), class:"btn btn-success" %>
              </td>
              <td>
                <%= link_to "Destroy", book_path(@book), class:"btn btn-danger", method: :DELETE, "data-confirm" => "本当に削除しますか？" %>
              </td>
            <% end %>
          </tr>
        </tbody>
      </table>
      
      <div>
        <table>
          <tbody>
            <% @book.book_comments.each do |book_comment| %>
              <tr>
                <td>
                  <%= image_tag book_comment.user.get_profile_image(100,100) %></br>
                  <%= book_comment.user.name %>
                </td>
                <td>
                  <%= book_comment.comment %>
                </td>
                <% if book_comment.user == current_user %>
                  <td>
                    <%= link_to "Destroy", book_book_comment_path(book_comment), class:"btn btn-danger", method: :delete %>
                  </td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= form_with model: [@book, @book_comment] do |f| %>
          <%= f.text_area :comment, rows: '5', cols: '100' %>
          <%= f.submit "送信" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px3 mx-auto">
      Welcome to <i class="fa-solid fa-book"></i><strong>Bookers</strong>!
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fa-solid fa-book"></i><strong>Bookers</strong> !!</h1>
      <p>in <i class="fa-solid fa-book"></i><strong>Bookers</strong>,</p>
      <p>you can share and exchange your opinions , inpressions , and emotions<p>
      <p>about various books!</p>
      
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3" %>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success btn-sm btn-block" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<fotter>
  <div class="container mt-5">
    <div class="row">
      <div class="mx-auto">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</fotter>

app/views/layouts/_header.html.erb
    <header>
       <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
         <div class="container">
           <a class="navbar-brand" href="/"><span>Bookers</span></a>
           <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li>
                  <%= link_to user_path(current_user), class:"nav-link text-light" do %>
                   <i class="fa-solid fa-house"></i> Home
                  <% end %>
                </li>
                <li>
                  <%= link_to users_path, class:"nav-link text-light" do %>
                   <i class="fa-solid fa-users"></i>
                   Users
                  <% end %>
                </li>
                <li>
                  <%= link_to books_path, class:"nav-link text-light" do %>
                   <i class="fa-solid fa-book-open"></i>
                   Books
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, class:"nav-link text-light", method: :delete do %>
                   <i class="fa-solid fa-right-from-bracket"></i>
                   Log out
                  <% end %>
                </li>
              <% else %>
                <li>
                  <%= link_to root_path, class:"nav-link text-light" do%>
                   <i class="fa-solid fa-house"></i> Home
                  <% end %>
                </li>
                <li>
                  <%= link_to about_path, class:"nav-link text-light" do %>
                   <i class="fa-solid fa-link"></i> About
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_registration_path, class:"nav-link text-light" do %>
                   <i class="fa-solid fa-user-plus"></i>
                   Sign up
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_session_path, class:"nav-link text-light" do %>
                   <i class="fa-solid fa-right-to-bracket"></i>
                   Log in
                  <% end %>
                </li>
              <% end %>
            </ul>
           </div>
          </div>
        </nav>
      </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/78ecf9ad97.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <main>
     <p><%= flash[:notice] %></p>
     <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/users/_info.html.erb
<h2>User info</h2>

     <%= image_tag user.get_profile_image(100,100) %>
    <table class="table">
      <tbody>
        <tr>
          <th>
            name
          </th>
          <td>
            <%= user.name %>
          </td>
        </tr>
        <tr>
          <th>
            introduction
          </th>
          <td>
            <%= user.introduction %>
          </td>
        </tr>
      </tbody>
    </table>
    <div class="row">
      <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
     <i class="fa-solid fa-user-gear"></i>
    <% end %>
    </div>
    

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
        <% if @user.errors.any? %>
          <%= @user.errors.count %> errors prohibited this obj from being saved:
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
  
        <%= form_with model: @user, url: user_path(@user), method: :patch do |f| %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"Name", class:"form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :Image %>
            <%= f.file_field :profile_image, placeholder: "Image", accept: "image/*" %>
          </div>
          <div class="form-group">
            <%= f.label :Introduction %>
            <%= f.text_area :introduction, id:"inputIntroduction", placeholder: "Introduction", class:"form-control" %>
          </div>
          <%= f.submit "Update User", class:"btn btn-secondary" %>
        <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'info', user: current_user %>
      <%= render 'books/new', book: @book %>
    </div>
    
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>
              image
            </th>
            <th>
              name
            </th>
            <th>
            </th>
            <th colspan="3"></th>
          </tr>
        </thead>
      
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= image_tag user.get_profile_image(100,100) %>
              </td>
              <td>
                <%= user.name %>
              </td>
              <td>
                <%= link_to "Show", user_path(user.id) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'info', user: @user %>
      <%= render 'books/new', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <%= render 'books/list', books: @user.books %>
    </div>
  </div>
</div>